In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
class neutral_network:
    def __init__(self,L,I,theta):
        self.L=L # matrix L
        self.I=I # matrix L
        self.theta=theta #weight neutral network that is small random value
        self.E=0 # total Error
    def step_function(self,y):
        # if input matrix is L then step function return 1 else return 0
        Y=np.array([[0,0]])
        if y[0][0]>0:
            Y[0][0]=1
        else:
             Y[0][0]=0
        # if input matrix is I then step function return 1 else return 0        
        if y[0][1]>0:
            Y[0][1]=1
        else:
             Y[0][1]=0        
        return Y
    
    
    def train_data(self,learning_rate,epochs):
        labale_target_L=0 #labale target fot L matrix
        labale_target_I=0 #labale target fot L matrix
        labale_target=[]  #2-dimentional node for L matrix and I matrix
        for i in range(epochs):
            matrix_sample = np.random.randint(0,2, size=(3,3)) #generate random matrix,dimension 3x3,elements is 0 or 1
            # if the generation random matrix is L then labale_target_L is 1 else 0 
            if (self.L==matrix_sample).all():
                labale_target_L=1
                
            else:
                labale_target_L=0
            # if the generation random matrix is I then labale_target_I is 1 else 0     
            if (self.I==matrix_sample).all():
                labale_target_I=1
                
            else:
                labale_target_I=0
            #create node for L matrix and I matrix    
            labale_target.append(labale_target_L) 
            labale_target.append(labale_target_I)
            matrix_sample=matrix_sample.reshape(-1,1) #covert the matrix to vector whit size 9x1
            matrix_sample_with_bias=np.append(matrix_sample,[1])# add bias node to neutral network
            matrix_sample_with_bias=matrix_sample_with_bias.reshape(-1,1)  #covert the matri_xwith_bias to vector whit size 10x1
            y_predict=self.step_function(np.dot (matrix_sample_with_bias.T, self.theta)) # sum(x.w) send to step_function
            
            Error=labale_target-y_predict #Error between real class and predict class
            self.E+=Error.sum() # total Error
            #if total Error is not  0 then modify weight
            if self.E!=0:
                self.theta+=learning_rate * Error * matrix_sample_with_bias
                #self.n_miss+=1
            labale_target=[]   
        #if total Error is not 0 then total number equal to 0 and start training step    
        if  self.E!=0:
            self.E=0
            self. train_data(learning_rate,epochs)
        else:
            return
    
    
    
    def output_node(self,matrix):
        labale_target_L=0 #labale target fot L matrix
        labale_target_I=0 #labale target fot L matrix
        labale_target=[]  #2-dimentional node for L matrix and I matrix
     
        if (self.L==matrix).all():
            labale_target_L=1
                
        else:
            labale_target_L=0
            # if the generation random matrix is I then labale_target_I is 1 else 0     
        if (self.I==matrix).all():
            labale_target_I=1
                
        else:
            abale_target_I=0
            #create node for L matrix and I matrix    
        labale_target.append(labale_target_L) 
        labale_target.append(labale_target_I)
        matrix=matrix.reshape(-1,1) #covert the matrix to vector whit size 9x1
        matrix_with_bias=np.append(matrix,[1])# add bias node to neutral network
        matrix_with_bias=matrix_with_bias.reshape(-1,1)  #covert the matri_xwith_bias to vector whit size 10x1
        return self.step_function(np.dot (matrix_with_bias.T, self.theta))# output for input matrix that determination the state matrix
        

# test algorithm with L and I

In [3]:
l=np.array([[1,0,0],[1,0,0],[1,1,1]])# definition L matrix
i=np.array([[0,1,0],[0,1,0],[0,1,0]]) # definition I matrix
theta= np.random.default_rng().uniform(0,1,(10,2)) # generating weights neutral network that is small random value


In [4]:
obj=neutral_network(l,i,theta)# get instance object,input include L and I and weight


In [5]:
obj.train_data(0.5,10000)# training data with learning rate 0.5 and epouchs 1000

In [6]:
l=np.array([[1,0,0],[1,0,0],[1,1,1]])
obj.theta # weight final after training
obj.output_node(l)# determination the state matrix

array([[1, 0]])

In [7]:
obj.output_node(i)

array([[0, 1]])

# changing input matrix

In [8]:
array = np.random.randint(0,2, size=(3,3)) #generate random matrix,dimension 3x3,elements is 0 or 1
array

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [9]:
obj.output_node(array) #determination the state matrix

array([[0, 0]])

In [10]:
change_L=np.array([[1,0,0],[1,1,0],[1,0,1]]) #change element of L matrix


In [11]:
obj.output_node(change_L)

array([[0, 0]])